apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.minio.user | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.password | b64enc | quote }}
