apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9001 
      targetPort: 9001
      protocol: TCP
      name: web-interface
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: s3
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
