name: pano-dev
services:
  postgres:
    container_name: pano-postgres
    image: docker.io/postgres:15-bookworm
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pano-dev
      POSTGRES_USER: pano-dev
      POSTGRES_PASSWORD: pano-dev
    volumes:
      - pano-dev-postgres-data:/var/lib/postgresql/data
    networks:
      - pano-dev-network
  garage:
    image: dxflrs/garage:v1.1.0
    restart: unless-stopped
    ports:
      - 3900:3900
    volumes:
      - /home/wilnil/Code/nycmeshnet/pano/dev/garage.toml:/etc/garage.toml
      - pano-dev-garage-meta:/var/lib/garage/meta
      - pano-dev-garage-data:/var/lib/garage/data
    networks:
      - pano-dev-network
volumes:
  pano-dev-postgres-data:
    name: pano-postgres-data
  pano-dev-garage-meta:
    name: pano-garage-meta
  pano-dev-garage-data:
    name: pano-garage-data
networks:
  pano-dev-network:
    name: pano-dev-network
