apiVersion: v1
kind: ConfigMap
metadata:
  name: pano-config 
  namespace: {{ .Values.namespace }}
data:
  MESHDB_ENVIRONMENT: {{ .Values.environment }}
  DD_ENV: {{ .Values.environment }}
  DD_TRACE_AGENT_URL: http://datadog-agent.datadog.svc.cluster.local:8126
