apiVersion: v1
kind: Secret
metadata:
  name: pano-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  PG_CONN: {{ .Values.pg.connection | b64enc | quote }}
  GARAGE_URL: {{ .Values.garage.url | b64enc | quote }}
  GARAGE_API_KEY: {{ .Values.garage.access_key | b64enc | quote }}
  GARAGE_SECRET: {{ .Values.garage.secret_key | b64enc | quote }}
  GARAGE_BUCKET: {{ .Values.garage.bucket | b64enc | quote }}
  GARAGE_SECURE: {{ .Values.garage.is_secure | quote | b64enc | quote }}
  MESHDB_ENDPOINT: {{ .Values.meshdb.endpoint | b64enc | quote }}
  MESHDB_TOKEN: {{ .Values.meshdb.token | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.google.client_id | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.client_secret | b64enc | quote }}
  PANO_FRONTEND_REDIRECT_URL: {{ .Values.pano.redirect | b64enc | quote }}
