apiVersion: v1
kind: Secret
metadata:
  name: pano-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  PG_CONN: {{ .Values.pg.connection | b64enc | quote }}
  MINIO_URL: {{ .Values.minio.url | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.access_key | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secret_key | b64enc | quote }}
  MINIO_BUCKET: {{ .Values.minio.bucket | b64enc | quote }}
  MINIO_SECURE: {{ .Values.minio.is_secure | quote | b64enc | quote }}
  MESHDB_ENDPOINT: {{ .Values.meshdb.endpoint | b64enc | quote }}
  MESHDB_TOKEN: {{ .Values.meshdb.token | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.google.client_id | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.client_secret | b64enc | quote }}
  PANO_FRONTEND_REDIRECT_URL: {{ .Values.pano.redirect | b64enc | quote }}
