apiVersion: v1
kind: Service
metadata:
  name: {{ include "pano.fullname" . }}
  labels:
    {{- include "pano.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: pano 
