name: Run Tests

on: 
  pull_request:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  run-django-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: docker.io/postgres:15-bookworm
        env:
          POSTGRES_DB: nycmesh-dev
          POSTGRES_USER: nycmesh
          POSTGRES_PASSWORD: abcd1234
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Start MinIO Container with Custom Command
        run: |
          docker run -d --name minio \
            -p 9000:9000 \
            -p 9001:9001 \
            -e MINIO_ROOT_USER=test \
            -e MINIO_ROOT_PASSWORD=test \
            minio/minio:latest \
            /bin/bash -c "minio server /data --console-address ':9001'"
      #- name: Ensure MinIO is running
      #  run: |
      #    echo "Waiting for MinIO to be ready..."
      #    sleep 5
      #    curl http://localhost:9001/minio/health/ready
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.11'
      - name: "Upgrade pip"
        run: "pip install --upgrade pip"
      - name: "Install package"
        run: pip install ".[dev]"
      - name: Run Django Tests
        env:
          DB_NAME: nycmesh-dev
          DB_USER: nycmesh
          DB_PASSWORD: abcd1234
          DB_HOST: localhost
          DB_PORT: 5432
          DJANGO_SECRET_KEY: k7j&!u07c%%97s!^a_6%mh_wbzo*$hl4lj_6c2ee6dk)y9!k88
          PELIAS_ADDRESS_PARSER_URL: http://localhost:6800/parser/parse
          QUERY_PSK: localdev
          NN_ASSIGN_PSK: localdev
          PANO_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DB_USER_RO: meshdb_ro
          DB_PASSWORD_RO: readonly
          JOIN_RECORD_BUCKET_NAME: meshdb-join-form-log
          JOIN_RECORD_PREFIX: dev-join-form-submissions
          AWS_ACCESS_KEY_ID: sampleaccesskey
          AWS_SECRET_ACCESS_KEY: samplesecretkey
          AWS_REGION: us-east-1
        run: coverage run pytest
      - name: Write coverage report to disk
        run: coverage html
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
